# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0339e9a64e35d3b544273d1cd26b011adcf9c2bcd00e45c9d1548b237d59f2ae38bc77cc390c15a9d6a79e27109d1c8bd314905027a65fcd53fea616673ee604

test:
  secret_key_base: ca25737988adf2b011f06437972e2475e441cd134e9648d694a879f1add83ab60a5382a4f0ee213dbd10ea025bc07121c11ed8a0fd80055786587847c9f8c070

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
